#!/usr/bin/env python3
"""Generate the deterministic D1 FLAC corpus and candidate manifest locally."""
from __future__ import annotations

import argparse
import json
import shutil
import subprocess
from pathlib import Path

from flac_corpus_common import (
    CASES,
    CASE_COLUMNS,
    CORPUS_REVISION,
    DERIVED_NEGATIVES,
    EXPECTED_FLAC_VERSION,
    EXPECTED_METAFLAC_VERSION,
    GENERATED_DIR,
    GENERATOR_LICENSE,
    MANIFEST_PATH,
    MANIFEST_SCHEMA_VERSION,
    NEGATIVE_COLUMNS,
    analysis_inventory,
    decode_command,
    derived_negative_bytes,
    encode_command,
    flac_test,
    make_pcm,
    metadata_inventory,
    require_tool,
    set_metadata,
    sha256_file,
    transport_manifest,
)


def generate(output_dir: Path) -> dict:
    flac = require_tool("flac", EXPECTED_FLAC_VERSION)
    metaflac = require_tool("metaflac", EXPECTED_METAFLAC_VERSION)

    if output_dir.exists():
        shutil.rmtree(output_dir)
    output_dir.mkdir(parents=True)

    manifest = {
        "schema_version": MANIFEST_SCHEMA_VERSION,
        "corpus_revision": CORPUS_REVISION,
        "toolchain": {
            "flac": EXPECTED_FLAC_VERSION,
            "metaflac": EXPECTED_METAFLAC_VERSION,
            "encoder_policy": "native FLAC, compression level 5, one encoding thread, verify enabled, no seektable, no padding unless case-specific, no preserved mtime",
        },
        "provenance": {
            "source_pcm": "algorithmically generated by tools/streams/flac_corpus_common.py",
            "third_party_media": False,
            "generated_media_committed": False,
            "licensing": GENERATOR_LICENSE,
        },
        "commands": {
            "encode_template": [
                "flac", "--force", "--silent", "--verify", "--threads=1",
                "--no-padding", "--no-seektable", "--no-preserve-modtime",
                "--force-raw-format", "--endian=little", "--sign=signed",
                "--channels={channels}", "--bps={bits_per_sample}",
                "--sample-rate={sample_rate_hz}", "-5",
                "--output-name=$GENERATED_DIR/{case_id}.flac",
                "$GENERATED_DIR/{case_id}.source.pcm"
            ],
            "decode_template": [
                "flac", "--decode", "--force", "--silent", "--force-raw-format",
                "--endian=little", "--sign=signed",
                "--output-name=$GENERATED_DIR/{case_id}.decoded.pcm",
                "$GENERATED_DIR/{case_id}.flac"
            ],
            "test_template": ["flac", "--test", "--silent", "$GENERATED_DIR/{case_id}.flac"],
            "metadata_policies": {
                "streaminfo_only": [
                    "metaflac --dont-use-padding --remove --block-type=VORBIS_COMMENT $GENERATED_DIR/{case_id}.flac"
                ],
                "deterministic_tags_padding17": [
                    "metaflac --dont-use-padding --remove-all-tags $GENERATED_DIR/{case_id}.flac",
                    "metaflac --dont-use-padding --set-tag=TITLE=MiSTer D1 deterministic metadata $GENERATED_DIR/{case_id}.flac",
                    "metaflac --dont-use-padding --set-tag=ARTIST=MiSTer-Media-Player-Audio $GENERATED_DIR/{case_id}.flac",
                    "metaflac --dont-use-padding --set-tag=COMMENT=synthetic project-generated corpus $GENERATED_DIR/{case_id}.flac",
                    "metaflac --dont-use-padding --set-tag=TRACKNUMBER=9 $GENERATED_DIR/{case_id}.flac",
                    "metaflac --add-padding=17 $GENERATED_DIR/{case_id}.flac"
                ]
            }
        },
        "claim_policy": "Observed encoded features are corpus evidence only. They do not by themselves constitute a decoder support claim.",
        "candidate_test_envelope": {
            "native_flac": True,
            "signed_pcm_bits": [16],
            "channels": [1, 2],
            "sample_rates_hz": [44100, 48000],
            "valid_unsupported_cases": ["flac_neg_02_unsupported_24bit_mono_44100"],
        },
        "transport_profiles": transport_manifest(),
        "case_columns": CASE_COLUMNS,
        "negative_columns": NEGATIVE_COLUMNS,
        "cases": [],
        "derived_negatives": [],
    }

    by_id: dict[str, Path] = {}
    for case in CASES:
        pcm_path = output_dir / f"{case.case_id}.source.pcm"
        flac_path = output_dir / f"{case.case_id}.flac"
        decoded_path = output_dir / f"{case.case_id}.decoded.pcm"

        pcm_path.write_bytes(make_pcm(case))
        enc = encode_command(flac, case, pcm_path, flac_path)
        subprocess.run(enc, check=True)
        metadata_commands = set_metadata(metaflac, case, flac_path)
        if not flac_test(flac, flac_path):
            raise SystemExit(f"reference FLAC test failed after metadata processing: {case.case_id}")

        dec = decode_command(flac, flac_path, decoded_path)
        subprocess.run(dec, check=True)
        if decoded_path.read_bytes() != pcm_path.read_bytes():
            raise SystemExit(f"reference decode mismatch: {case.case_id}")

        analysis = analysis_inventory(flac, flac_path)
        frame_offsets = analysis.pop("frame_offsets")
        metadata = metadata_inventory(metaflac, flac_path)
        entry = [
            case.case_id,
            case.group_id,
            case.classification,
            case.sample_rate,
            case.channels,
            case.bits_per_sample,
            case.sample_count,
            case.pattern,
            "deterministic_tags_padding17" if case.metadata_case else "streaminfo_only",
            sha256_file(pcm_path),
            sha256_file(flac_path),
            sha256_file(decoded_path),
            flac_path.stat().st_size,
            analysis["frame_count"],
            analysis["block_sizes"],
            analysis["channel_assignments"],
            analysis["subframe_types"],
            analysis["fixed_orders"],
            analysis["lpc_orders"],
            analysis["rice_partition_orders"],
            analysis["wasted_bits"],
            metadata["block_types"],
            metadata["block_lengths"],
        ]
        manifest["cases"].append(entry)
        by_id[case.case_id] = flac_path

    for spec in DERIVED_NEGATIVES:
        base_path = by_id[spec["base_case_id"]]
        out_path = output_dir / f"{spec['case_id']}.flac"
        out_path.write_bytes(derived_negative_bytes(spec, base_path.read_bytes()))
        actual_test = "pass" if flac_test(flac, out_path) else "fail"
        if actual_test != spec["reference_test"]:
            raise SystemExit(
                f"negative reference-test mismatch for {spec['case_id']}: expected {spec['reference_test']}, got {actual_test}"
            )
        manifest["derived_negatives"].append([
            spec["case_id"], spec["group_id"], spec["classification"],
            spec["base_case_id"], spec["mutation"], spec["reference_test"],
            out_path.name, sha256_file(out_path), out_path.stat().st_size,
        ])

    candidate_path = output_dir / "manifest.generated.json"
    candidate_path.write_text(json.dumps(manifest, sort_keys=True, separators=(",", ":")) + "\n")
    return manifest


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output-dir", type=Path, default=GENERATED_DIR)
    parser.add_argument(
        "--update-manifest",
        action="store_true",
        help="Replace the tracked expected manifest with the freshly generated candidate.",
    )
    args = parser.parse_args()

    manifest = generate(args.output_dir)
    text = json.dumps(manifest, sort_keys=True, separators=(",", ":")) + "\n"
    if args.update_manifest:
        MANIFEST_PATH.write_text(text)
        print(f"updated {MANIFEST_PATH}")
    else:
        if not MANIFEST_PATH.exists():
            raise SystemExit(f"tracked manifest missing: {MANIFEST_PATH}; use --update-manifest only for an approved corpus revision")
        if MANIFEST_PATH.read_text() != text:
            raise SystemExit(
                "generated manifest differs from tracked manifest; inspect generated/flac/manifest.generated.json before updating"
            )
        print("generated corpus matches tracked manifest")
    print(f"generated {len(manifest['cases'])} valid/unsupported cases and {len(manifest['derived_negatives'])} invalid cases")


if __name__ == "__main__":
    main()
